In [1]:
import torch
import timm
import os
from PIL import Image
from roboflow import Roboflow
from torchvision import transforms
from torch.utils.data import DataLoader, Dataset
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report
from tqdm import tqdm
import torch.nn as nn
import torch.optim as optim
from torchvision.datasets import ImageFolder

In [2]:
rf = Roboflow(api_key="DV3LuuCyQmUxhaklG7P0")
project = rf.workspace("ciptooo").project("ddr-rg3uk")
version = project.version(1)
dataset = version.download("folder")

loading Roboflow workspace...
loading Roboflow project...


In [3]:
train_dir = os.path.join(dataset.location, "train")
test_dir = os.path.join(dataset.location, "test")
val_dir = os.path.join(dataset.location, "valid")

In [4]:
# Menambahkan drop_rate=0.2 (20% dropout) untuk regularisasi
model = timm.create_model(
    'mobilevitv2_100.cvnets_in1k',
    pretrained=True,
    num_classes=6,
    drop_rate=0.2  # <-- PERUBAHAN 1: MENAMBAHKAN DROPOUT
)

In [5]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
print(f"Model moved to {device}.")

Model moved to cuda.


In [6]:
# Menambahkan Data Augmentation untuk data training
train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.5), # <-- PERUBAHAN 2: DATA AUGMENTATION
    transforms.RandomRotation(15),         # <-- PERUBAHAN 3: DATA AUGMENTATION
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# Transformasi untuk validasi dan tes tidak perlu augmentasi
val_test_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

In [7]:
# Gunakan train_transform untuk data training
train_dataset = ImageFolder(root=train_dir, transform=train_transform)

# Gunakan val_test_transform untuk validasi dan tes
val_dataset = ImageFolder(root=val_dir, transform=val_test_transform)
test_dataset = ImageFolder(root=test_dir, transform=val_test_transform)


train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True, num_workers=2) # Batch size 16 adalah awal yang baik
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False, num_workers=2)

In [8]:
# --- 4. Training and Validation Loop ---
from torch.optim import AdamW
# Define loss function and optimizer
criterion = nn.CrossEntropyLoss().to(device)
optimizer = AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)
num_epochs = 100
best_val_loss = float('inf')
save_path = "best_model_mobilevitv2.pth"

print("\nStarting model training...")
for epoch in range(num_epochs):
    # Training
    model.train()
    epoch_train_loss = 0
    train_preds, train_targets = [], []
    train_progress_bar = tqdm(train_loader, desc=f"Epoch [{epoch+1}/{num_epochs}] Training")
    for inputs, targets in train_progress_bar:
        inputs, targets = inputs.to(device), targets.to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, targets)
        loss.backward()
        optimizer.step()

        epoch_train_loss += loss.item()
        _, predicted = torch.max(outputs.data, 1)
        train_preds.extend(predicted.cpu().numpy())
        train_targets.extend(targets.cpu().numpy())
        train_progress_bar.set_postfix(loss=loss.item())

    avg_train_loss = epoch_train_loss / len(train_loader)
    train_accuracy = accuracy_score(train_targets, train_preds) * 100

    # Validation
    model.eval()
    epoch_val_loss = 0
    val_preds, val_targets = [], []
    with torch.no_grad():
        val_progress_bar = tqdm(val_loader, desc=f"Epoch [{epoch+1}/{num_epochs}] Validation")
        for inputs, targets in val_progress_bar:
            inputs, targets = inputs.to(device), targets.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            epoch_val_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            val_preds.extend(predicted.cpu().numpy())
            val_targets.extend(targets.cpu().numpy())

    avg_val_loss = epoch_val_loss / len(val_loader)
    val_accuracy = accuracy_score(val_targets, val_preds) * 100

    print(f"Epoch [{epoch+1}/{num_epochs}] -> Train Loss: {avg_train_loss:.4f}, Train Acc: {train_accuracy:.2f}% | Val Loss: {avg_val_loss:.4f}, Val Acc: {val_accuracy:.2f}%")

    if avg_val_loss < best_val_loss:
        best_val_loss = avg_val_loss
        torch.save(model.state_dict(), save_path)
        print(f"✅ New best model saved at epoch {epoch+1} with Val Loss: {best_val_loss:.4f}")

print("\nTraining complete.")



Starting model training...


Epoch [1/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 18.81it/s]


Epoch [1/100] -> Train Loss: 0.8159, Train Acc: 71.15% | Val Loss: 0.7006, Val Acc: 76.66%
✅ New best model saved at epoch 1 with Val Loss: 0.7006


Epoch [2/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.60it/s]


Epoch [2/100] -> Train Loss: 0.6451, Train Acc: 77.09% | Val Loss: 0.6116, Val Acc: 78.76%
✅ New best model saved at epoch 2 with Val Loss: 0.6116


Epoch [3/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.29it/s]


Epoch [3/100] -> Train Loss: 0.6058, Train Acc: 78.76% | Val Loss: 0.6142, Val Acc: 78.21%


Epoch [4/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.03it/s]


Epoch [4/100] -> Train Loss: 0.5719, Train Acc: 79.99% | Val Loss: 0.5975, Val Acc: 80.01%
✅ New best model saved at epoch 4 with Val Loss: 0.5975


Epoch [5/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.57it/s]


Epoch [5/100] -> Train Loss: 0.5304, Train Acc: 81.10% | Val Loss: 0.6614, Val Acc: 75.05%


Epoch [6/100] Validation: 100%|██████████| 86/86 [00:03<00:00, 21.61it/s]


Epoch [6/100] -> Train Loss: 0.5151, Train Acc: 81.67% | Val Loss: 0.5802, Val Acc: 79.82%
✅ New best model saved at epoch 6 with Val Loss: 0.5802


Epoch [7/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.41it/s]


Epoch [7/100] -> Train Loss: 0.4830, Train Acc: 83.01% | Val Loss: 0.5288, Val Acc: 82.10%
✅ New best model saved at epoch 7 with Val Loss: 0.5288


Epoch [8/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.48it/s]


Epoch [8/100] -> Train Loss: 0.4658, Train Acc: 83.71% | Val Loss: 0.6135, Val Acc: 78.32%


Epoch [9/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.27it/s]


Epoch [9/100] -> Train Loss: 0.4483, Train Acc: 83.73% | Val Loss: 0.5801, Val Acc: 81.77%


Epoch [10/100] Validation: 100%|██████████| 86/86 [00:03<00:00, 21.61it/s]


Epoch [10/100] -> Train Loss: 0.4258, Train Acc: 84.62% | Val Loss: 0.5732, Val Acc: 81.15%


Epoch [11/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.04it/s]


Epoch [11/100] -> Train Loss: 0.3999, Train Acc: 85.45% | Val Loss: 0.5196, Val Acc: 82.69%
✅ New best model saved at epoch 11 with Val Loss: 0.5196


Epoch [12/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.35it/s]


Epoch [12/100] -> Train Loss: 0.3817, Train Acc: 85.88% | Val Loss: 0.5045, Val Acc: 82.07%
✅ New best model saved at epoch 12 with Val Loss: 0.5045


Epoch [13/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.24it/s]


Epoch [13/100] -> Train Loss: 0.3675, Train Acc: 86.25% | Val Loss: 0.5506, Val Acc: 81.73%


Epoch [14/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.34it/s]


Epoch [14/100] -> Train Loss: 0.3559, Train Acc: 87.51% | Val Loss: 0.5286, Val Acc: 82.62%


Epoch [15/100] Validation: 100%|██████████| 86/86 [00:03<00:00, 22.37it/s]


Epoch [15/100] -> Train Loss: 0.3260, Train Acc: 87.82% | Val Loss: 0.5608, Val Acc: 81.73%


Epoch [16/100] Validation: 100%|██████████| 86/86 [00:03<00:00, 21.82it/s]


Epoch [16/100] -> Train Loss: 0.3211, Train Acc: 88.69% | Val Loss: 0.6734, Val Acc: 81.33%


Epoch [17/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.00it/s]


Epoch [17/100] -> Train Loss: 0.2959, Train Acc: 89.04% | Val Loss: 0.6687, Val Acc: 81.04%


Epoch [18/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.90it/s]


Epoch [18/100] -> Train Loss: 0.2842, Train Acc: 89.69% | Val Loss: 0.6193, Val Acc: 82.40%


Epoch [19/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.62it/s]


Epoch [19/100] -> Train Loss: 0.2646, Train Acc: 90.38% | Val Loss: 0.5889, Val Acc: 81.33%


Epoch [20/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.11it/s]


Epoch [20/100] -> Train Loss: 0.2531, Train Acc: 90.67% | Val Loss: 0.6481, Val Acc: 82.21%


Epoch [21/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.85it/s]


Epoch [21/100] -> Train Loss: 0.2284, Train Acc: 91.88% | Val Loss: 0.6361, Val Acc: 81.04%


Epoch [22/100] Validation: 100%|██████████| 86/86 [00:03<00:00, 21.67it/s]


Epoch [22/100] -> Train Loss: 0.2340, Train Acc: 91.55% | Val Loss: 0.7212, Val Acc: 77.62%


Epoch [23/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.76it/s]


Epoch [23/100] -> Train Loss: 0.2149, Train Acc: 91.90% | Val Loss: 0.6507, Val Acc: 80.60%


Epoch [24/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.85it/s]


Epoch [24/100] -> Train Loss: 0.2054, Train Acc: 92.51% | Val Loss: 0.6330, Val Acc: 82.29%


Epoch [25/100] Validation: 100%|██████████| 86/86 [00:03<00:00, 21.53it/s]


Epoch [25/100] -> Train Loss: 0.1980, Train Acc: 92.70% | Val Loss: 0.6650, Val Acc: 82.65%


Epoch [26/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.78it/s]


Epoch [26/100] -> Train Loss: 0.1800, Train Acc: 93.43% | Val Loss: 0.6951, Val Acc: 80.63%


Epoch [27/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.37it/s]


Epoch [27/100] -> Train Loss: 0.1763, Train Acc: 93.60% | Val Loss: 0.7095, Val Acc: 82.03%


Epoch [28/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.49it/s]


Epoch [28/100] -> Train Loss: 0.1696, Train Acc: 93.88% | Val Loss: 0.8198, Val Acc: 81.22%


Epoch [29/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.49it/s]


Epoch [29/100] -> Train Loss: 0.1553, Train Acc: 94.56% | Val Loss: 0.7573, Val Acc: 81.26%


Epoch [30/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.98it/s]


Epoch [30/100] -> Train Loss: 0.1560, Train Acc: 94.38% | Val Loss: 0.7802, Val Acc: 78.61%


Epoch [31/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.36it/s]


Epoch [31/100] -> Train Loss: 0.1519, Train Acc: 94.79% | Val Loss: 0.8100, Val Acc: 81.37%


Epoch [32/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.08it/s]


Epoch [32/100] -> Train Loss: 0.1439, Train Acc: 94.75% | Val Loss: 0.7237, Val Acc: 82.14%


Epoch [33/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.82it/s]


Epoch [33/100] -> Train Loss: 0.1379, Train Acc: 95.15% | Val Loss: 0.7374, Val Acc: 82.43%


Epoch [34/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.10it/s]


Epoch [34/100] -> Train Loss: 0.1263, Train Acc: 95.68% | Val Loss: 0.9139, Val Acc: 81.55%


Epoch [35/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.42it/s]


Epoch [35/100] -> Train Loss: 0.1254, Train Acc: 95.60% | Val Loss: 0.8118, Val Acc: 81.40%


Epoch [36/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.31it/s]


Epoch [36/100] -> Train Loss: 0.1389, Train Acc: 94.91% | Val Loss: 0.8068, Val Acc: 80.78%


Epoch [37/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.03it/s]


Epoch [37/100] -> Train Loss: 0.1136, Train Acc: 95.90% | Val Loss: 0.9218, Val Acc: 80.41%


Epoch [38/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.56it/s]


Epoch [38/100] -> Train Loss: 0.1196, Train Acc: 95.85% | Val Loss: 0.8283, Val Acc: 81.15%


Epoch [39/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.25it/s]


Epoch [39/100] -> Train Loss: 0.1158, Train Acc: 95.82% | Val Loss: 0.7604, Val Acc: 80.56%


Epoch [40/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.82it/s]


Epoch [40/100] -> Train Loss: 0.1190, Train Acc: 95.88% | Val Loss: 0.7721, Val Acc: 81.84%


Epoch [41/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.86it/s]


Epoch [41/100] -> Train Loss: 0.1014, Train Acc: 96.37% | Val Loss: 0.8425, Val Acc: 81.77%


Epoch [42/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.33it/s]


Epoch [42/100] -> Train Loss: 0.1178, Train Acc: 95.71% | Val Loss: 0.7855, Val Acc: 81.59%


Epoch [43/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.22it/s]


Epoch [43/100] -> Train Loss: 0.0981, Train Acc: 96.45% | Val Loss: 0.9046, Val Acc: 78.57%


Epoch [44/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.21it/s]


Epoch [44/100] -> Train Loss: 0.1075, Train Acc: 96.32% | Val Loss: 0.8264, Val Acc: 83.09%


Epoch [45/100] Validation: 100%|██████████| 86/86 [00:03<00:00, 21.75it/s]


Epoch [45/100] -> Train Loss: 0.1014, Train Acc: 96.43% | Val Loss: 0.8967, Val Acc: 81.84%


Epoch [46/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.85it/s]


Epoch [46/100] -> Train Loss: 0.1033, Train Acc: 96.29% | Val Loss: 0.8357, Val Acc: 80.85%


Epoch [47/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.81it/s]


Epoch [47/100] -> Train Loss: 0.0886, Train Acc: 96.89% | Val Loss: 1.0063, Val Acc: 80.41%


Epoch [48/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.85it/s]


Epoch [48/100] -> Train Loss: 0.1026, Train Acc: 96.40% | Val Loss: 1.1121, Val Acc: 82.32%


Epoch [49/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.86it/s]


Epoch [49/100] -> Train Loss: 0.0980, Train Acc: 96.55% | Val Loss: 0.9731, Val Acc: 78.79%


Epoch [50/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.30it/s]


Epoch [50/100] -> Train Loss: 0.0911, Train Acc: 96.93% | Val Loss: 0.8102, Val Acc: 81.04%


Epoch [51/100] Validation: 100%|██████████| 86/86 [00:03<00:00, 21.88it/s]


Epoch [51/100] -> Train Loss: 0.0808, Train Acc: 97.24% | Val Loss: 0.8968, Val Acc: 82.40%


Epoch [52/100] Validation: 100%|██████████| 86/86 [00:03<00:00, 21.54it/s]


Epoch [52/100] -> Train Loss: 0.0870, Train Acc: 97.02% | Val Loss: 0.8925, Val Acc: 81.44%


Epoch [53/100] Validation: 100%|██████████| 86/86 [00:03<00:00, 21.73it/s]


Epoch [53/100] -> Train Loss: 0.0919, Train Acc: 96.72% | Val Loss: 0.8754, Val Acc: 81.15%


Epoch [54/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.70it/s]


Epoch [54/100] -> Train Loss: 0.0883, Train Acc: 96.66% | Val Loss: 0.8751, Val Acc: 81.77%


Epoch [55/100] Validation: 100%|██████████| 86/86 [00:03<00:00, 22.02it/s]


Epoch [55/100] -> Train Loss: 0.0794, Train Acc: 97.23% | Val Loss: 0.9441, Val Acc: 80.45%


Epoch [56/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.29it/s]


Epoch [56/100] -> Train Loss: 0.0819, Train Acc: 97.36% | Val Loss: 0.9920, Val Acc: 81.44%


Epoch [57/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.20it/s]


Epoch [57/100] -> Train Loss: 0.0849, Train Acc: 97.01% | Val Loss: 0.9449, Val Acc: 81.11%


Epoch [58/100] Validation: 100%|██████████| 86/86 [00:03<00:00, 21.85it/s]


Epoch [58/100] -> Train Loss: 0.0766, Train Acc: 97.30% | Val Loss: 1.0346, Val Acc: 81.66%


Epoch [59/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.29it/s]


Epoch [59/100] -> Train Loss: 0.0817, Train Acc: 97.23% | Val Loss: 0.8769, Val Acc: 81.07%


Epoch [60/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.06it/s]


Epoch [60/100] -> Train Loss: 0.0741, Train Acc: 97.41% | Val Loss: 0.9396, Val Acc: 82.03%


Epoch [61/100] Validation: 100%|██████████| 86/86 [00:03<00:00, 21.91it/s]


Epoch [61/100] -> Train Loss: 0.0723, Train Acc: 97.48% | Val Loss: 0.8825, Val Acc: 80.85%


Epoch [62/100] Validation: 100%|██████████| 86/86 [00:03<00:00, 21.83it/s]


Epoch [62/100] -> Train Loss: 0.0838, Train Acc: 97.17% | Val Loss: 0.8146, Val Acc: 81.18%


Epoch [63/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.45it/s]


Epoch [63/100] -> Train Loss: 0.0714, Train Acc: 97.42% | Val Loss: 0.9436, Val Acc: 81.44%


Epoch [64/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.59it/s]


Epoch [64/100] -> Train Loss: 0.0808, Train Acc: 97.03% | Val Loss: 0.8712, Val Acc: 80.37%


Epoch [65/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.19it/s]


Epoch [65/100] -> Train Loss: 0.0594, Train Acc: 98.14% | Val Loss: 1.0057, Val Acc: 80.15%


Epoch [66/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.28it/s]


Epoch [66/100] -> Train Loss: 0.0758, Train Acc: 97.46% | Val Loss: 0.9127, Val Acc: 80.26%


Epoch [67/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.94it/s]


Epoch [67/100] -> Train Loss: 0.0740, Train Acc: 97.40% | Val Loss: 0.9923, Val Acc: 79.13%


Epoch [68/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.51it/s]


Epoch [68/100] -> Train Loss: 0.0695, Train Acc: 97.62% | Val Loss: 0.9728, Val Acc: 81.96%


Epoch [69/100] Validation: 100%|██████████| 86/86 [00:03<00:00, 22.02it/s]


Epoch [69/100] -> Train Loss: 0.0578, Train Acc: 97.98% | Val Loss: 0.8738, Val Acc: 81.92%


Epoch [70/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.66it/s]


Epoch [70/100] -> Train Loss: 0.0753, Train Acc: 97.41% | Val Loss: 0.9293, Val Acc: 81.66%


Epoch [71/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.69it/s]


Epoch [71/100] -> Train Loss: 0.0635, Train Acc: 97.61% | Val Loss: 1.0351, Val Acc: 81.55%


Epoch [72/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.80it/s]


Epoch [72/100] -> Train Loss: 0.0528, Train Acc: 98.36% | Val Loss: 0.9494, Val Acc: 81.55%


Epoch [73/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.45it/s]


Epoch [73/100] -> Train Loss: 0.0645, Train Acc: 97.69% | Val Loss: 0.9594, Val Acc: 81.99%


Epoch [74/100] Validation: 100%|██████████| 86/86 [00:03<00:00, 21.65it/s]


Epoch [74/100] -> Train Loss: 0.0664, Train Acc: 97.59% | Val Loss: 1.0111, Val Acc: 81.70%


Epoch [75/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.41it/s]


Epoch [75/100] -> Train Loss: 0.0829, Train Acc: 97.24% | Val Loss: 0.8905, Val Acc: 80.78%


Epoch [76/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.22it/s]


Epoch [76/100] -> Train Loss: 0.0586, Train Acc: 98.06% | Val Loss: 0.9005, Val Acc: 81.81%


Epoch [77/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.31it/s]


Epoch [77/100] -> Train Loss: 0.0495, Train Acc: 98.42% | Val Loss: 1.1093, Val Acc: 80.15%


Epoch [78/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.46it/s]


Epoch [78/100] -> Train Loss: 0.0605, Train Acc: 97.87% | Val Loss: 1.0109, Val Acc: 81.92%


Epoch [79/100] Validation: 100%|██████████| 86/86 [00:03<00:00, 21.61it/s]


Epoch [79/100] -> Train Loss: 0.0587, Train Acc: 98.07% | Val Loss: 0.9711, Val Acc: 81.00%


Epoch [80/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.20it/s]


Epoch [80/100] -> Train Loss: 0.0634, Train Acc: 97.69% | Val Loss: 1.0368, Val Acc: 81.62%


Epoch [81/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.92it/s]


Epoch [81/100] -> Train Loss: 0.0766, Train Acc: 97.47% | Val Loss: 0.9729, Val Acc: 80.34%


Epoch [82/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.16it/s]


Epoch [82/100] -> Train Loss: 0.0433, Train Acc: 98.48% | Val Loss: 0.9965, Val Acc: 82.14%


Epoch [83/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.41it/s]


Epoch [83/100] -> Train Loss: 0.0658, Train Acc: 97.68% | Val Loss: 1.0435, Val Acc: 82.51%


Epoch [84/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.15it/s]


Epoch [84/100] -> Train Loss: 0.0640, Train Acc: 97.85% | Val Loss: 0.8949, Val Acc: 82.36%


Epoch [85/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.31it/s]


Epoch [85/100] -> Train Loss: 0.0536, Train Acc: 98.17% | Val Loss: 0.8742, Val Acc: 80.52%


Epoch [86/100] Validation: 100%|██████████| 86/86 [00:03<00:00, 21.57it/s]


Epoch [86/100] -> Train Loss: 0.0572, Train Acc: 98.07% | Val Loss: 1.1622, Val Acc: 81.51%


Epoch [87/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.30it/s]


Epoch [87/100] -> Train Loss: 0.0492, Train Acc: 98.33% | Val Loss: 1.0861, Val Acc: 81.96%


Epoch [88/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.47it/s]


Epoch [88/100] -> Train Loss: 0.0523, Train Acc: 98.27% | Val Loss: 1.0354, Val Acc: 80.30%


Epoch [89/100] Validation: 100%|██████████| 86/86 [00:03<00:00, 22.32it/s]


Epoch [89/100] -> Train Loss: 0.0544, Train Acc: 98.17% | Val Loss: 1.0377, Val Acc: 82.62%


Epoch [90/100] Validation: 100%|██████████| 86/86 [00:03<00:00, 22.07it/s]


Epoch [90/100] -> Train Loss: 0.0487, Train Acc: 98.33% | Val Loss: 1.0972, Val Acc: 81.84%


Epoch [91/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.44it/s]


Epoch [91/100] -> Train Loss: 0.0635, Train Acc: 97.90% | Val Loss: 1.0641, Val Acc: 79.49%


Epoch [92/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.28it/s]


Epoch [92/100] -> Train Loss: 0.0454, Train Acc: 98.49% | Val Loss: 0.9585, Val Acc: 81.92%


Epoch [93/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.29it/s]


Epoch [93/100] -> Train Loss: 0.0534, Train Acc: 98.26% | Val Loss: 0.9389, Val Acc: 80.74%


Epoch [94/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.78it/s]


Epoch [94/100] -> Train Loss: 0.0507, Train Acc: 98.34% | Val Loss: 0.9587, Val Acc: 80.85%


Epoch [95/100] Validation: 100%|██████████| 86/86 [00:03<00:00, 21.60it/s]


Epoch [95/100] -> Train Loss: 0.0450, Train Acc: 98.35% | Val Loss: 0.9758, Val Acc: 80.30%


Epoch [96/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.81it/s]


Epoch [96/100] -> Train Loss: 0.0711, Train Acc: 97.68% | Val Loss: 0.8768, Val Acc: 83.35%


Epoch [97/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 21.46it/s]


Epoch [97/100] -> Train Loss: 0.0364, Train Acc: 98.69% | Val Loss: 0.9987, Val Acc: 82.25%


Epoch [98/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.68it/s]


Epoch [98/100] -> Train Loss: 0.0478, Train Acc: 98.44% | Val Loss: 1.0009, Val Acc: 80.52%


Epoch [99/100] Validation: 100%|██████████| 86/86 [00:03<00:00, 21.51it/s]


Epoch [99/100] -> Train Loss: 0.0519, Train Acc: 98.46% | Val Loss: 0.9591, Val Acc: 81.77%


Epoch [100/100] Validation: 100%|██████████| 86/86 [00:03<00:00, 21.60it/s]

Epoch [100/100] -> Train Loss: 0.0528, Train Acc: 98.29% | Val Loss: 0.9238, Val Acc: 79.93%

Training complete.


In [9]:
# --- 5. Final Evaluation on Test Set ---
print("\nLoading best model for final evaluation...")
# Load the best model weights
# If using DataParallel, the state_dict keys are prefixed with 'module.'
# We need to load it into a model with the same architecture.
eval_model = timm.create_model('mobilevitv2_100.cvnets_in1k', num_classes=6)
if torch.cuda.device_count() > 1:
    eval_model = nn.DataParallel(eval_model)
eval_model.load_state_dict(torch.load(save_path))
eval_model.to(device)
eval_model.eval()
print("Model loaded. Starting testing...")

test_preds, test_targets = [], []
with torch.no_grad():
    for inputs, targets in tqdm(test_loader, desc="Testing"):
        inputs, targets = inputs.to(device), targets.to(device)
        outputs = eval_model(inputs)
        _, preds = torch.max(outputs, 1)
        test_preds.extend(preds.cpu().numpy())
        test_targets.extend(targets.cpu().numpy())


Loading best model for final evaluation...
Model loaded. Starting testing...


Testing: 100%|██████████| 43/43 [00:02<00:00, 17.32it/s]


In [10]:
# --- 6. Report and Save Results ---
accuracy = accuracy_score(test_targets, test_preds)
conf_matrix = confusion_matrix(test_targets, test_preds)
report = classification_report(test_targets, test_preds, target_names=test_dataset.classes, zero_division=0)

results_text = f"""
=================================================
      Fine-Tuning Results for mobilevitv2_100
=================================================

Final Test Accuracy: {accuracy * 100:.2f}%

Confusion Matrix:
{conf_matrix}

Classification Report:
{report}
"""

print(results_text)

# Save results to a file
with open("fine_tuning_report.txt", "w") as f:
    f.write(results_text)

print(f"✅ Final report saved to 'fine_tuning_report.txt'")
print(f"✅ Best model weights saved to '{save_path}'")


      Fine-Tuning Results for mobilevitv2_100

Final Test Accuracy: 81.76%

Confusion Matrix:
[[546  20  28   0   0   8]
 [ 26  11  24   0   0   0]
 [ 39  19 375  13   6   8]
 [  0   1  12  10   5   0]
 [  4   1  11   3  64   2]
 [  5   0   5   0   7 101]]

Classification Report:
              precision    recall  f1-score   support

     class_0       0.88      0.91      0.89       602
     class_1       0.21      0.18      0.19        61
     class_2       0.82      0.82      0.82       460
     class_3       0.38      0.36      0.37        28
     class_4       0.78      0.75      0.77        85
     class_5       0.85      0.86      0.85       118

    accuracy                           0.82      1354
   macro avg       0.66      0.64      0.65      1354
weighted avg       0.81      0.82      0.81      1354


✅ Final report saved to 'fine_tuning_report.txt'
✅ Best model weights saved to 'best_model_mobilevitv2.pth'
