In [19]:
import torch
import timm
import os
from PIL import Image
from roboflow import Roboflow
from torchvision import transforms
from torch.utils.data import DataLoader, Dataset
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report
from tqdm import tqdm
import torch.nn as nn
import torch.optim as optim
from torchvision.datasets import ImageFolder
from torch.optim.lr_scheduler import ReduceLROnPlateau

Loading Dataset dari Roboflow

In [20]:
rf = Roboflow(api_key="DV3LuuCyQmUxhaklG7P0")
project = rf.workspace("ciptooo").project("ddr-rg3uk")
version = project.version(1)
dataset = version.download("folder")

loading Roboflow workspace...
loading Roboflow project...


In [21]:
train_dir = os.path.join(dataset.location, "train")
test_dir = os.path.join(dataset.location, "test")
val_dir = os.path.join(dataset.location, "valid")

Load Model

In [ ]:
model = timm.create_model(
    'mobilevitv2_100.cvnets_in1k',
    pretrained=True,
    num_classes=6,
    drop_rate=0.2 # Drop rate 0.2 untuk mengurangi overfitting
)

In [23]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
print(f"Model moved to {device}.")

Model moved to cuda.


Transform

In [ ]:
train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.5), 
    transforms.RandomRotation(15),         
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

val_test_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

Dataset Loader

In [ ]:
# Gunakan train_transform untuk data training
train_dataset = ImageFolder(root=train_dir, transform=train_transform)

# Gunakan val_test_transform untuk validasi dan tes
val_dataset = ImageFolder(root=val_dir, transform=val_test_transform)
test_dataset = ImageFolder(root=test_dir, transform=val_test_transform)


train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True, num_workers=2) # Batch size 16 untuk training
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False, num_workers=2) # Batch size 32 untuk validasi
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False, num_workers=2) # Batch size 32 untuk testing

Training dan Validasi

In [ ]:
from torch.optim import AdamW

# Define loss function, optimizer, dan learning rate scheduler
criterion = nn.CrossEntropyLoss().to(device)
optimizer = AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)
scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.1, patience=5)
num_epochs = 100
best_val_loss = float('inf')
save_path = "best_model_mobilevitv2_fine-tuning2.pth"

print("\nStarting model training...")
for epoch in range(num_epochs):
    # Training
    model.train()
    epoch_train_loss = 0
    train_preds, train_targets = [], []
    train_progress_bar = tqdm(train_loader, desc=f"Epoch [{epoch+1}/{num_epochs}] Training")
    for inputs, targets in train_progress_bar:
        inputs, targets = inputs.to(device), targets.to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, targets)
        loss.backward()
        optimizer.step()

        epoch_train_loss += loss.item()
        _, predicted = torch.max(outputs.data, 1)
        train_preds.extend(predicted.cpu().numpy())
        train_targets.extend(targets.cpu().numpy())
        train_progress_bar.set_postfix(loss=loss.item())

    avg_train_loss = epoch_train_loss / len(train_loader)
    train_accuracy = accuracy_score(train_targets, train_preds) * 100

    # Validation
    model.eval()
    epoch_val_loss = 0
    val_preds, val_targets = [], []
    with torch.no_grad():
        val_progress_bar = tqdm(val_loader, desc=f"Epoch [{epoch+1}/{num_epochs}] Validation")
        for inputs, targets in val_progress_bar:
            inputs, targets = inputs.to(device), targets.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            epoch_val_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            val_preds.extend(predicted.cpu().numpy())
            val_targets.extend(targets.cpu().numpy())

    avg_val_loss = epoch_val_loss / len(val_loader)
    val_accuracy = accuracy_score(val_targets, val_preds) * 100

    print(f"Epoch [{epoch+1}/{num_epochs}] -> Train Loss: {avg_train_loss:.4f}, Train Acc: {train_accuracy:.2f}% | Val Loss: {avg_val_loss:.4f}, Val Acc: {val_accuracy:.2f}%")
    
    scheduler.step(avg_val_loss)
    
    if avg_val_loss < best_val_loss:
        best_val_loss = avg_val_loss
        torch.save(model.state_dict(), save_path)
        print(f"✅ New best model saved at epoch {epoch+1} with Val Loss: {best_val_loss:.4f}")

print("\nTraining complete.")



Starting model training...


Epoch [1/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.09it/s]


Epoch [1/100] -> Train Loss: 0.8346, Train Acc: 70.41% | Val Loss: 0.6940, Val Acc: 74.31%
✅ New best model saved at epoch 1 with Val Loss: 0.6940


Epoch [2/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.32it/s]


Epoch [2/100] -> Train Loss: 0.6568, Train Acc: 76.75% | Val Loss: 0.5896, Val Acc: 79.93%
✅ New best model saved at epoch 2 with Val Loss: 0.5896


Epoch [3/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.08it/s]


Epoch [3/100] -> Train Loss: 0.6029, Train Acc: 78.76% | Val Loss: 0.5947, Val Acc: 77.95%


Epoch [4/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.23it/s]


Epoch [4/100] -> Train Loss: 0.5679, Train Acc: 79.74% | Val Loss: 0.5818, Val Acc: 80.19%
✅ New best model saved at epoch 4 with Val Loss: 0.5818


Epoch [5/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.97it/s]


Epoch [5/100] -> Train Loss: 0.5377, Train Acc: 80.81% | Val Loss: 0.6065, Val Acc: 78.32%


Epoch [6/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.11it/s]


Epoch [6/100] -> Train Loss: 0.5123, Train Acc: 81.60% | Val Loss: 0.5442, Val Acc: 81.44%
✅ New best model saved at epoch 6 with Val Loss: 0.5442


Epoch [7/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.55it/s]


Epoch [7/100] -> Train Loss: 0.4901, Train Acc: 82.55% | Val Loss: 0.5834, Val Acc: 79.53%


Epoch [8/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.50it/s]


Epoch [8/100] -> Train Loss: 0.4757, Train Acc: 83.39% | Val Loss: 0.5488, Val Acc: 80.71%


Epoch [9/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.02it/s]


Epoch [9/100] -> Train Loss: 0.4467, Train Acc: 84.00% | Val Loss: 0.5177, Val Acc: 82.21%
✅ New best model saved at epoch 9 with Val Loss: 0.5177


Epoch [10/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.40it/s]


Epoch [10/100] -> Train Loss: 0.4259, Train Acc: 84.43% | Val Loss: 0.5876, Val Acc: 78.72%


Epoch [11/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.08it/s]


Epoch [11/100] -> Train Loss: 0.4197, Train Acc: 84.97% | Val Loss: 0.5982, Val Acc: 80.89%


Epoch [12/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.02it/s]


Epoch [12/100] -> Train Loss: 0.4001, Train Acc: 85.51% | Val Loss: 0.5500, Val Acc: 81.62%


Epoch [13/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.51it/s]


Epoch [13/100] -> Train Loss: 0.3662, Train Acc: 86.53% | Val Loss: 0.5776, Val Acc: 81.92%


Epoch [14/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.06it/s]


Epoch [14/100] -> Train Loss: 0.3505, Train Acc: 87.10% | Val Loss: 0.5646, Val Acc: 80.96%


Epoch [15/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.83it/s]


Epoch [15/100] -> Train Loss: 0.3357, Train Acc: 87.98% | Val Loss: 0.6032, Val Acc: 79.46%


Epoch [16/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.05it/s]


Epoch [16/100] -> Train Loss: 0.2392, Train Acc: 90.98% | Val Loss: 0.4994, Val Acc: 84.49%
✅ New best model saved at epoch 16 with Val Loss: 0.4994


Epoch [17/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.82it/s]


Epoch [17/100] -> Train Loss: 0.1834, Train Acc: 93.42% | Val Loss: 0.5201, Val Acc: 84.23%


Epoch [18/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.14it/s]


Epoch [18/100] -> Train Loss: 0.1530, Train Acc: 94.44% | Val Loss: 0.5268, Val Acc: 84.56%


Epoch [19/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.17it/s]


Epoch [19/100] -> Train Loss: 0.1427, Train Acc: 95.08% | Val Loss: 0.5536, Val Acc: 84.34%


Epoch [20/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.41it/s]


Epoch [20/100] -> Train Loss: 0.1240, Train Acc: 95.73% | Val Loss: 0.6034, Val Acc: 84.20%


Epoch [21/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.20it/s]


Epoch [21/100] -> Train Loss: 0.1085, Train Acc: 96.19% | Val Loss: 0.6140, Val Acc: 84.09%


Epoch [22/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.35it/s]


Epoch [22/100] -> Train Loss: 0.0931, Train Acc: 96.78% | Val Loss: 0.6356, Val Acc: 84.05%


Epoch [23/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.38it/s]


Epoch [23/100] -> Train Loss: 0.0839, Train Acc: 96.87% | Val Loss: 0.6181, Val Acc: 84.01%


Epoch [24/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.14it/s]


Epoch [24/100] -> Train Loss: 0.0871, Train Acc: 97.12% | Val Loss: 0.6161, Val Acc: 84.09%


Epoch [25/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.50it/s]


Epoch [25/100] -> Train Loss: 0.0814, Train Acc: 97.33% | Val Loss: 0.6263, Val Acc: 84.09%


Epoch [26/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.12it/s]


Epoch [26/100] -> Train Loss: 0.0803, Train Acc: 97.49% | Val Loss: 0.6287, Val Acc: 84.53%


Epoch [27/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.28it/s]


Epoch [27/100] -> Train Loss: 0.0821, Train Acc: 97.36% | Val Loss: 0.6475, Val Acc: 84.75%


Epoch [28/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.31it/s]


Epoch [28/100] -> Train Loss: 0.0749, Train Acc: 97.48% | Val Loss: 0.6242, Val Acc: 84.53%


Epoch [29/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.35it/s]


Epoch [29/100] -> Train Loss: 0.0777, Train Acc: 97.38% | Val Loss: 0.6402, Val Acc: 84.75%


Epoch [30/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.55it/s]


Epoch [30/100] -> Train Loss: 0.0789, Train Acc: 97.30% | Val Loss: 0.6302, Val Acc: 84.12%


Epoch [31/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.18it/s]


Epoch [31/100] -> Train Loss: 0.0709, Train Acc: 97.89% | Val Loss: 0.6348, Val Acc: 84.31%


Epoch [32/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.82it/s]


Epoch [32/100] -> Train Loss: 0.0763, Train Acc: 97.21% | Val Loss: 0.6414, Val Acc: 84.16%


Epoch [33/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.17it/s]


Epoch [33/100] -> Train Loss: 0.0744, Train Acc: 97.50% | Val Loss: 0.6404, Val Acc: 84.67%


Epoch [34/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.45it/s]


Epoch [34/100] -> Train Loss: 0.0689, Train Acc: 97.69% | Val Loss: 0.6349, Val Acc: 83.87%


Epoch [35/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.67it/s]


Epoch [35/100] -> Train Loss: 0.0711, Train Acc: 97.88% | Val Loss: 0.6432, Val Acc: 84.86%


Epoch [36/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.60it/s]


Epoch [36/100] -> Train Loss: 0.0717, Train Acc: 97.54% | Val Loss: 0.6278, Val Acc: 84.20%


Epoch [37/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.47it/s]


Epoch [37/100] -> Train Loss: 0.0758, Train Acc: 97.50% | Val Loss: 0.6294, Val Acc: 84.49%


Epoch [38/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.62it/s]


Epoch [38/100] -> Train Loss: 0.0721, Train Acc: 97.66% | Val Loss: 0.6245, Val Acc: 84.38%


Epoch [39/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.16it/s]


Epoch [39/100] -> Train Loss: 0.0748, Train Acc: 97.36% | Val Loss: 0.6357, Val Acc: 84.31%


Epoch [40/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.10it/s]


Epoch [40/100] -> Train Loss: 0.0710, Train Acc: 97.57% | Val Loss: 0.6306, Val Acc: 84.27%


Epoch [41/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.15it/s]


Epoch [41/100] -> Train Loss: 0.0733, Train Acc: 97.73% | Val Loss: 0.6323, Val Acc: 84.34%


Epoch [42/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.43it/s]


Epoch [42/100] -> Train Loss: 0.0690, Train Acc: 97.57% | Val Loss: 0.6323, Val Acc: 84.75%


Epoch [43/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.19it/s]


Epoch [43/100] -> Train Loss: 0.0772, Train Acc: 97.37% | Val Loss: 0.6405, Val Acc: 84.20%


Epoch [44/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.36it/s]


Epoch [44/100] -> Train Loss: 0.0736, Train Acc: 97.48% | Val Loss: 0.6416, Val Acc: 83.76%


Epoch [45/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.56it/s]


Epoch [45/100] -> Train Loss: 0.0720, Train Acc: 97.55% | Val Loss: 0.6383, Val Acc: 84.45%


Epoch [46/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.34it/s]


Epoch [46/100] -> Train Loss: 0.0774, Train Acc: 97.33% | Val Loss: 0.6546, Val Acc: 84.16%


Epoch [47/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.25it/s]


Epoch [47/100] -> Train Loss: 0.0773, Train Acc: 97.52% | Val Loss: 0.6426, Val Acc: 84.64%


Epoch [48/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.65it/s]


Epoch [48/100] -> Train Loss: 0.0758, Train Acc: 97.41% | Val Loss: 0.6379, Val Acc: 84.60%


Epoch [49/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.29it/s]


Epoch [49/100] -> Train Loss: 0.0747, Train Acc: 97.32% | Val Loss: 0.6298, Val Acc: 84.60%


Epoch [50/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.98it/s]


Epoch [50/100] -> Train Loss: 0.0738, Train Acc: 97.47% | Val Loss: 0.6435, Val Acc: 84.42%


Epoch [51/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.62it/s]


Epoch [51/100] -> Train Loss: 0.0728, Train Acc: 97.57% | Val Loss: 0.6332, Val Acc: 84.56%


Epoch [52/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.35it/s]


Epoch [52/100] -> Train Loss: 0.0714, Train Acc: 97.66% | Val Loss: 0.6662, Val Acc: 84.45%


Epoch [53/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.16it/s]


Epoch [53/100] -> Train Loss: 0.0733, Train Acc: 97.56% | Val Loss: 0.6307, Val Acc: 84.27%


Epoch [54/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.04it/s]


Epoch [54/100] -> Train Loss: 0.0706, Train Acc: 97.50% | Val Loss: 0.6397, Val Acc: 84.31%


Epoch [55/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.52it/s]


Epoch [55/100] -> Train Loss: 0.0706, Train Acc: 97.53% | Val Loss: 0.6477, Val Acc: 84.56%


Epoch [56/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.88it/s]


Epoch [56/100] -> Train Loss: 0.0729, Train Acc: 97.47% | Val Loss: 0.6283, Val Acc: 84.27%


Epoch [57/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.50it/s]


Epoch [57/100] -> Train Loss: 0.0743, Train Acc: 97.42% | Val Loss: 0.6398, Val Acc: 84.09%


Epoch [58/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.67it/s]


Epoch [58/100] -> Train Loss: 0.0736, Train Acc: 97.37% | Val Loss: 0.6446, Val Acc: 84.82%


Epoch [59/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.99it/s]


Epoch [59/100] -> Train Loss: 0.0785, Train Acc: 97.42% | Val Loss: 0.6311, Val Acc: 84.42%


Epoch [60/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.51it/s]


Epoch [60/100] -> Train Loss: 0.0802, Train Acc: 97.29% | Val Loss: 0.6375, Val Acc: 84.60%


Epoch [61/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.27it/s]


Epoch [61/100] -> Train Loss: 0.0708, Train Acc: 97.53% | Val Loss: 0.6441, Val Acc: 83.94%


Epoch [62/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.48it/s]


Epoch [62/100] -> Train Loss: 0.0739, Train Acc: 97.53% | Val Loss: 0.6442, Val Acc: 84.09%


Epoch [63/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.95it/s]


Epoch [63/100] -> Train Loss: 0.0662, Train Acc: 97.68% | Val Loss: 0.6337, Val Acc: 84.38%


Epoch [64/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.67it/s]


Epoch [64/100] -> Train Loss: 0.0789, Train Acc: 97.36% | Val Loss: 0.6384, Val Acc: 84.20%


Epoch [65/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.43it/s]


Epoch [65/100] -> Train Loss: 0.0823, Train Acc: 97.22% | Val Loss: 0.6494, Val Acc: 84.75%


Epoch [66/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.67it/s]


Epoch [66/100] -> Train Loss: 0.0682, Train Acc: 97.58% | Val Loss: 0.6282, Val Acc: 84.05%


Epoch [67/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.26it/s]


Epoch [67/100] -> Train Loss: 0.0714, Train Acc: 97.50% | Val Loss: 0.6463, Val Acc: 84.49%


Epoch [68/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.67it/s]


Epoch [68/100] -> Train Loss: 0.0742, Train Acc: 97.41% | Val Loss: 0.6344, Val Acc: 84.45%


Epoch [69/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.53it/s]


Epoch [69/100] -> Train Loss: 0.0774, Train Acc: 97.37% | Val Loss: 0.6441, Val Acc: 84.42%


Epoch [70/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.02it/s]


Epoch [70/100] -> Train Loss: 0.0719, Train Acc: 97.54% | Val Loss: 0.6278, Val Acc: 84.01%


Epoch [71/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.41it/s]


Epoch [71/100] -> Train Loss: 0.0728, Train Acc: 97.47% | Val Loss: 0.6362, Val Acc: 84.05%


Epoch [72/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.13it/s]


Epoch [72/100] -> Train Loss: 0.0682, Train Acc: 97.62% | Val Loss: 0.6360, Val Acc: 83.90%


Epoch [73/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.32it/s]


Epoch [73/100] -> Train Loss: 0.0685, Train Acc: 97.72% | Val Loss: 0.6476, Val Acc: 84.23%


Epoch [74/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.76it/s]


Epoch [74/100] -> Train Loss: 0.0735, Train Acc: 97.42% | Val Loss: 0.6375, Val Acc: 83.79%


Epoch [75/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.55it/s]


Epoch [75/100] -> Train Loss: 0.0730, Train Acc: 97.46% | Val Loss: 0.6431, Val Acc: 84.64%


Epoch [76/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.29it/s]


Epoch [76/100] -> Train Loss: 0.0724, Train Acc: 97.70% | Val Loss: 0.6383, Val Acc: 84.27%


Epoch [77/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.19it/s]


Epoch [77/100] -> Train Loss: 0.0740, Train Acc: 97.46% | Val Loss: 0.6323, Val Acc: 84.42%


Epoch [78/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.29it/s]


Epoch [78/100] -> Train Loss: 0.0756, Train Acc: 97.43% | Val Loss: 0.6376, Val Acc: 84.53%


Epoch [79/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.25it/s]


Epoch [79/100] -> Train Loss: 0.0785, Train Acc: 97.46% | Val Loss: 0.6358, Val Acc: 84.12%


Epoch [80/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.36it/s]


Epoch [80/100] -> Train Loss: 0.0678, Train Acc: 97.77% | Val Loss: 0.6365, Val Acc: 84.64%


Epoch [81/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.26it/s]


Epoch [81/100] -> Train Loss: 0.0821, Train Acc: 97.26% | Val Loss: 0.6515, Val Acc: 84.38%


Epoch [82/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.30it/s]


Epoch [82/100] -> Train Loss: 0.0794, Train Acc: 97.33% | Val Loss: 0.6454, Val Acc: 84.20%


Epoch [83/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.64it/s]


Epoch [83/100] -> Train Loss: 0.0786, Train Acc: 97.47% | Val Loss: 0.6411, Val Acc: 84.34%


Epoch [84/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.30it/s]


Epoch [84/100] -> Train Loss: 0.0758, Train Acc: 97.47% | Val Loss: 0.6314, Val Acc: 84.16%


Epoch [85/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.06it/s]


Epoch [85/100] -> Train Loss: 0.0765, Train Acc: 97.64% | Val Loss: 0.6382, Val Acc: 84.23%


Epoch [86/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.34it/s]


Epoch [86/100] -> Train Loss: 0.0726, Train Acc: 97.64% | Val Loss: 0.6539, Val Acc: 84.93%


Epoch [87/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.13it/s]


Epoch [87/100] -> Train Loss: 0.0754, Train Acc: 97.66% | Val Loss: 0.6408, Val Acc: 84.05%


Epoch [88/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.54it/s]


Epoch [88/100] -> Train Loss: 0.0753, Train Acc: 97.56% | Val Loss: 0.6407, Val Acc: 84.53%


Epoch [89/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.43it/s]


Epoch [89/100] -> Train Loss: 0.0757, Train Acc: 97.60% | Val Loss: 0.6430, Val Acc: 84.60%


Epoch [90/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.70it/s]


Epoch [90/100] -> Train Loss: 0.0761, Train Acc: 97.47% | Val Loss: 0.6294, Val Acc: 84.31%


Epoch [91/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.38it/s]


Epoch [91/100] -> Train Loss: 0.0707, Train Acc: 97.73% | Val Loss: 0.6486, Val Acc: 84.45%


Epoch [92/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.59it/s]


Epoch [92/100] -> Train Loss: 0.0717, Train Acc: 97.63% | Val Loss: 0.6413, Val Acc: 84.42%


Epoch [93/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.27it/s]


Epoch [93/100] -> Train Loss: 0.0740, Train Acc: 97.36% | Val Loss: 0.6343, Val Acc: 84.86%


Epoch [94/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.23it/s]


Epoch [94/100] -> Train Loss: 0.0726, Train Acc: 97.66% | Val Loss: 0.6426, Val Acc: 84.27%


Epoch [95/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.25it/s]


Epoch [95/100] -> Train Loss: 0.0728, Train Acc: 97.63% | Val Loss: 0.6340, Val Acc: 84.45%


Epoch [96/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.61it/s]


Epoch [96/100] -> Train Loss: 0.0754, Train Acc: 97.37% | Val Loss: 0.6295, Val Acc: 84.31%


Epoch [97/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.60it/s]


Epoch [97/100] -> Train Loss: 0.0709, Train Acc: 97.59% | Val Loss: 0.6534, Val Acc: 84.49%


Epoch [98/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 19.62it/s]


Epoch [98/100] -> Train Loss: 0.0686, Train Acc: 97.87% | Val Loss: 0.6447, Val Acc: 84.53%


Epoch [99/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.53it/s]


Epoch [99/100] -> Train Loss: 0.0739, Train Acc: 97.64% | Val Loss: 0.6489, Val Acc: 84.64%


Epoch [100/100] Validation: 100%|██████████| 86/86 [00:04<00:00, 20.33it/s]

Epoch [100/100] -> Train Loss: 0.0769, Train Acc: 97.26% | Val Loss: 0.6422, Val Acc: 84.42%

Training complete.


Testing

In [ ]:
print("\nLoading best model for final evaluation...")

# Load model terbaik
eval_model = timm.create_model('mobilevitv2_100.cvnets_in1k', num_classes=6)
if torch.cuda.device_count() > 1:
    eval_model = nn.DataParallel(eval_model)
eval_model.load_state_dict(torch.load(save_path))
eval_model.to(device)
eval_model.eval()
print("Model loaded. Starting testing...")

test_preds, test_targets = [], []
with torch.no_grad():
    for inputs, targets in tqdm(test_loader, desc="Testing"):
        inputs, targets = inputs.to(device), targets.to(device)
        outputs = eval_model(inputs)
        _, preds = torch.max(outputs, 1)
        test_preds.extend(preds.cpu().numpy())
        test_targets.extend(targets.cpu().numpy())


Loading best model for final evaluation...
Model loaded. Starting testing...


Testing: 100%|██████████| 43/43 [00:02<00:00, 20.36it/s]


Classification Report

In [ ]:
accuracy = accuracy_score(test_targets, test_preds)
conf_matrix = confusion_matrix(test_targets, test_preds)
report = classification_report(test_targets, test_preds, target_names=test_dataset.classes, zero_division=0)

results_text = f"""
=================================================
      Fine-Tuning Results for mobilevitv2_100
=================================================

Final Test Accuracy: {accuracy * 100:.2f}%

Confusion Matrix:
{conf_matrix}

Classification Report:
{report}
"""

print(results_text)

# Save results to a file
with open("fine_tuning2_report.txt", "w") as f:
    f.write(results_text)

print(f"✅ Final report saved to 'fine_tuning_report.txt'")
print(f"✅ Best model weights saved to '{save_path}'")


      Fine-Tuning Results for mobilevitv2_100

Final Test Accuracy: 82.57%

Confusion Matrix:
[[548  12  34   0   0   8]
 [ 20  18  23   0   0   0]
 [ 40  29 365   7  12   7]
 [  0   1  14  10   3   0]
 [  3   0  10   2  67   3]
 [  1   0   4   0   3 110]]

Classification Report:
              precision    recall  f1-score   support

     class_0       0.90      0.91      0.90       602
     class_1       0.30      0.30      0.30        61
     class_2       0.81      0.79      0.80       460
     class_3       0.53      0.36      0.43        28
     class_4       0.79      0.79      0.79        85
     class_5       0.86      0.93      0.89       118

    accuracy                           0.83      1354
   macro avg       0.70      0.68      0.69      1354
weighted avg       0.82      0.83      0.82      1354


✅ Final report saved to 'fine_tuning_report.txt'
✅ Best model weights saved to 'best_model_mobilevitv2_fine-tuning2.pth'
